#!/usr/bin/env python3
"""
Email Sender Module for Astrological Reports
Sends zipped astrological reports via email with secure authentication.
"""

import json
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
from typing import Dict, Optional
from dataclasses import dataclass

@dataclass
class EmailConfig:
    """Email configuration settings."""
    enabled: bool = False
    smtp_server: str = "smtp.gmail.com"
    smtp_port: int = 587
    sender_email: str = ""
    sender_password: str = ""  # App-specific password
    recipient_email: str = "langjam350@gmail.com"

class EmailSender:
    """Handles sending astrological reports via email."""

    def __init__(self, config_file: str = "email_config.json"):
        """Initialize email sender with configuration."""
        self.config_file = config_file
        self.config = self._load_config()

    def _load_config(self) -> EmailConfig:
        """Load email configuration from file."""
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, 'r') as f:
                    data = json.load(f)
                return EmailConfig(**data)
            except Exception as e:
                print(f"Error loading email config: {e}")
                return EmailConfig()
        else:
            # Create default config file
            default_config = EmailConfig()
            self._save_config(default_config)
            return default_config

    def _save_config(self, config: EmailConfig) -> None:
        """Save configuration to file."""
        try:
            with open(self.config_file, 'w') as f:
                json.dump(config.__dict__, f, indent=2)
        except Exception as e:
            print(f"Error saving email config: {e}")

    def update_config(self, **kwargs) -> None:
        """Update configuration settings."""
        for key, value in kwargs.items():
            if hasattr(self.config, key):
                setattr(self.config, key, value)
        self._save_config(self.config)

    def send_weekly_report(self, zip_file_path: str, week_info: str = "") -> bool:
        """Send weekly astrological report via email."""
        if not self.config.enabled:
            print("Email sending is disabled")
            return False

        if not os.path.exists(zip_file_path):
            print(f"ZIP file not found: {zip_file_path}")
            return False

        try:
            # Create message
            message = MIMEMultipart()
            message["From"] = self.config.sender_email
            message["To"] = self.config.recipient_email
            message["Subject"] = f"🔮 Weekly Astrological Report {week_info}"

            # Email body
            body = f"""
🌟 Your Weekly Astrological Report is Ready! 🌟

This week's comprehensive astrological analysis includes:
• Daily forecasts with planetary transits
• Historical context and world events perspective
• Ideal timing breakdown for each day
• Visual birth chart and current transits
• AI-enhanced user-friendly interpretations

{week_info}

Generated with complete privacy - all analysis done locally on your computer.

May the stars guide your week ahead! ✨

---
Generated by your Local Astrological Analysis Program
No external AI services used - your data stays private
"""

            message.attach(MIMEText(body, "plain"))

            # Attach ZIP file
            with open(zip_file_path, "rb") as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())

            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {os.path.basename(zip_file_path)}'
            )
            message.attach(part)

            # Send email
            context = ssl.create_default_context()
            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.config.sender_email, self.config.sender_password)
                text = message.as_string()
                server.sendmail(self.config.sender_email, self.config.recipient_email, text)

            print(f"✅ Weekly report emailed successfully to {self.config.recipient_email}")
            return True

        except Exception as e:
            print(f"❌ Failed to send email: {e}")
            return False

    def test_connection(self) -> bool:
        """Test email connection and authentication."""
        if not self.config.enabled:
            print("Email is disabled in configuration")
            return False

        if not self.config.sender_email or not self.config.sender_password:
            print("Email credentials not configured")
            return False

        try:
            context = ssl.create_default_context()
            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.config.sender_email, self.config.sender_password)

            print("✅ Email connection successful!")
            return True

        except Exception as e:
            print(f"❌ Email connection failed: {e}")
            print("\nTroubleshooting:")
            print("1. Enable 2-factor authentication on Gmail")
            print("2. Generate app-specific password: https://myaccount.google.com/apppasswords")
            print("3. Use app password (not your regular Gmail password)")
            return False

def setup_email_interactive():
    """Interactive email setup."""
    print("🔮 Email Setup for Astrological Reports")
    print("=" * 50)

    sender = EmailSender()
    current_config = sender.config

    print(f"Current configuration:")
    print(f"  Enabled: {current_config.enabled}")
    print(f"  Sender: {current_config.sender_email}")
    print(f"  Recipient: {current_config.recipient_email}")
    print()

    enable = input("Enable weekly email reports? (y/n): ").lower().strip()

    if enable in ['y', 'yes']:
        print("\nGmail Setup Required:")
        print("1. Enable 2-factor authentication on your Gmail account")
        print("2. Go to: https://myaccount.google.com/apppasswords")
        print("3. Generate an app-specific password for this program")
        print("4. Use that app password below (NOT your regular password)")
        print()

        sender_email = input("Your Gmail address: ").strip()
        app_password = input("App-specific password (from step 3): ").strip()

        if sender_email and app_password:
            sender.update_config(
                enabled=True,
                sender_email=sender_email,
                sender_password=app_password,
                recipient_email="langjam350@gmail.com"
            )

            print("\nTesting email connection...")
            if sender.test_connection():
                print("✅ Email setup complete!")
                print("You'll receive weekly reports every Saturday at midnight.")
            else:
                print("❌ Setup failed. Please check your credentials.")
        else:
            print("Invalid input. Email setup cancelled.")
    else:
        sender.update_config(enabled=False)
        print("Email reports disabled.")

if __name__ == "__main__":
    setup_email_interactive()